spring.application.name=camunda-spring
camunda.bpm.authorization.enabled=true
onesignal.app-id=9c30f6cf-c413-426d-b6fa-36c1d83ae3a7
onesignal.api-key=os_v2_app_tqypnt6ecnbg3nx2g3a5qoxdu7jolulfdbgurp5wpaxtay6gry7huzqslvmh37lpipgf7u3fbpnb6ljwgrrz7f65m3k3rvqvqdtawoq