spring.application.name=camunda-spring
camunda.bpm.authorization.enabled=true
onesignal.app-id=9c30f6cf-c413-426d-b6fa-36c1d83ae3a7
onesignal.api-key=os_v2_app_tqypnt6ecnbg3nx2g3a5qoxdu7fwfclr432exrfxwosubtlr24rqidwmjofhbozxigonghi7rig5qsn4rhdx5phfj3qnmkc4o35q2xi